title: Project Poster
email: addisonfreeman91@gmail.com
description: 'This website is serving as a project poster for the team that worked on this during the Autumn 2020 semester'
logo: "https://digitallearning.eletsonline.com/wp-content/uploads/2016/02/Ohio-State-University.jpg"
baseurl: "https://osumc-cultural-awareness.github.io/Project-Poster-AU2020/"
url: "https://osumc-cultural-awareness.github.io/Project-Poster-AU2020/"
remote_theme: daviddarnes/alembic
permalink: pretty

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Build settings
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jemoji
- jekyll-remote-theme

# Header nav
heading_anchors: true
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Config
  url: /configuration/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
