
title: Project Poster
email:
description: >- 
  This website is serving as a project poster for the team 
  that worked on this during the Autumn 2020 semester
# logo: https://library.kissclipart.com/20181218/ow/kissclipart-ohio-state-sign-clipart-ohio-state-university-ohio-1539583922cc1c54.png


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
